export const FILTER_MOVIE = 'FILTER_MOVIE';
export const FILTER_MOVIE_SUCCESS = 'FILTER_MOVIE_SUCCESS';

export const GET_MOVIE = 'GET_MOVIE';
export const GET_MOVIE_ERROR = 'GET_MOVIE_ERROR';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';

export const GET_DATA_MOVIE = 'GET_DATA_MOVIE';
export const GET_DATA_MOVIE_SUCCESS = 'GET_DATA_MOVIE_SUCCESS';
export const GET_DATA_MOVIE_ERROR = 'GET_DATA_MOVIE_ERROR';
